#-----------------------------------------------------------------------------------
# - A Python-wrapping module for CMake using PyBindGen
#
# Modified from the UseSWIG module from the cmake2.8 release.
#
# Defines the following macros:
#   PYBINDGEN_GENERATE_BINDINGS(module_name module_list)
#     - Generates the Python bindings for each module in the list
#
# Internal macros to do the work:
#   PYBINDGEN_REGISTER_MODULE(name)
#     - Builds list of Python source code and generated C++ code
# 
#
# Variables that must be set before calling PYBINDGEN_GENERATE_BINDINGS:
#   PYBINDGEN_DIR
#     - Location of the python source code to build the bindings
#   PYTHON_EXE
#     - Python executable
#   PYTHON_LIB_DIR
#     - Python lib (typically obtained from the executable root)
#
# Optional variables
#   PYBINDGEN_ADDITIONAL_ARGS
#     - Additional arguments to follow the command in PYBINDGEN_GENERATE_BINDINGS
#
# To get the names of the generated source
# use: ${PYBINDGEN_GENERATED_SOURCE}
#-----------------------------------------------------------------------------------

# Initialize the list of Python source code
set(PYBINDGEN_SOURCE)

# Initialize the list of C++ code generated by PyBindGen
set(PYBINDGEN_GENERATED_SOURCE)

#
# INTERNAL: Build up the lists of source files and generated files to track
# outputs and dependencies for the build
#
macro(PYBINDGEN_REGISTER_MODULE _module)
  if (EXISTS "${PYBINDGEN_DIR}/${_module}Module.py")
    set(_source "${PYBINDGEN_DIR}/${_module}Module.py")
  else()
    if (EXISTS "${PROJECT_BINARY_DIR}/src/PBGWraps/${_module}Module.py")
      set(_source "${PROJECT_BINARY_DIR}/src/PBGWraps/${_module}Module.py")
    else()
      message(FATAL_ERROR "Could not find source file ${_module}Module.py")
    endif()
  endif()
  list(APPEND PYBINDGEN_SOURCE ${_source})
  list(APPEND PYBINDGEN_GENERATED_SOURCE "${PYBINDGEN_MODULE_NAME}_${_module}.C")
endmacro()

#
# Runs "Python PolytopeModulesBindings.py" to generate the bindings.
# This is where the PyBindGen module is actually used. Calls the previous
# internal macros to generate the source file lists
#
macro(PYBINDGEN_GENERATE_BINDINGS module_list)
  list(APPEND PYBINDGEN_SOURCE "${PYBINDGEN_MODULE_NAME}Bindings.py")
  list(APPEND PYBINDGEN_GENERATED_SOURCE "${PYBINDGEN_MODULE_NAME}.C")
  set(PYBINDGEN_GENERATED_HEADER "${PYBINDGEN_MODULE_NAME}.hh")
  foreach(it ${module_list})
    PYBINDGEN_REGISTER_MODULE(${it})
  endforeach()
  add_custom_command(
    OUTPUT ${PYBINDGEN_GENERATED_SOURCE} ${PYBINDGEN_GENERATED_HEADER}
    COMMAND ${PYTHON_EXE} 
      ${PYBINDGEN_DIR}/${PYBINDGEN_MODULE_NAME}Bindings.py
      ${PYBINDGEN_ADDITIONAL_ARGS}
    DEPENDS ${PYBINDGEN_SOURCE}
    )
endmacro()